import Sidebar from "@/components/Sidebar";
import "@/styles/globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { extendTheme } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

const colors = {
  brand: {
    400: "#DA0155",
  },
};

const theme = extendTheme({ colors });

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Peace Garden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {router.pathname == "/" ? (
          <Component {...pageProps} />
        ) : (
          <Sidebar>
            <Component {...pageProps} />
          </Sidebar>
        )}
      </main>
    </ChakraProvider>
  );
}

export default MyApp;
