import React from "react";

import {
  Box,
  Flex,
  Heading,
  Input,
  Button,
  Stack,
  Stat,
  StatLabel,
  StatNumber,
  StatHelpText,
  StatArrow,
  StatGroup,
  HStack,
  Text,
} from "@chakra-ui/react";
import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import { Chart as ChartJS } from "chart.js/auto";
import { Bar } from "react-chartjs-2";
import { faker } from "@faker-js/faker";

const labels = ["January", "February", "March", "April", "May", "June", "July"];

export const data = {
  labels,
  datasets: [
    {
      label: "  Orders",
      data: labels.map(() => faker.datatype.number({ min: 0, max: 1000 })),
      backgroundColor: "#DA0155",
    },
    {
      label: "Revenue",
      data: labels.map(() => faker.datatype.number({ min: 0, max: 1000 })),
      backgroundColor: "#fc6767",
    },
  ],
};
const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Peace Garden</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar>
          <Flex justify={"space-evenly"} gap={20} px={4}>
            <Stat
              px={10}
              py={6}
              bgGradient={"linear(to-bl, #DA0155, #fc6767)"}
              color="#fff"
              alignItems={"center"}
              display={"flex"}
              width={"fit-content"}
              rounded={"2xl"}
            >
              <StatLabel>{`Monthly Revenue`}</StatLabel>
              <StatNumber>$32918</StatNumber>
              <StatHelpText>
                <StatArrow type="increase" />
                33.09%
              </StatHelpText>
            </Stat>
            <Stat
              px={10}
              py={2}
              bgGradient={"linear(to-bl, #DA0155, #fc6767)"}
              color="#fff"
              alignItems={"center"}
              display={"flex"}
              width={"fit-content"}
              rounded={"2xl"}
            >
              <StatLabel>{`Today's Revenue`}</StatLabel>
              <StatNumber>$598</StatNumber>
              <StatHelpText>
                <StatArrow type="decrease" />
                9.05%
              </StatHelpText>
            </Stat>
            <Stat
              px={10}
              py={2}
              bgGradient={"linear(to-bl, #DA0155, #fc6767)"}
              color="#fff"
              alignItems={"center"}
              display={"flex"}
              width={"fit-content"}
              rounded={"2xl"}
            >
              <StatLabel>{`Total Units sold`}</StatLabel>
              <StatNumber>237</StatNumber>
              <StatHelpText>
                <StatArrow type="increase" />
                36.05%
              </StatHelpText>
            </Stat>
          </Flex>
          <Flex justify={"space-around"} mt={10} height={"50vh"}>
            <Bar
              data={data}
              options={{ responsive: false }}
              height={290}
              width={400}
              style={{
                background: "#fff",
                padding: "20px",
                borderRadius: "15px",
              }}
            />
            <Bar
              data={data}
              options={{ responsive: false }}
              height={290}
              width={400}
              style={{
                background: "#fff",
                padding: "20px",
                borderRadius: "15px",
              }}
            />
          </Flex>
        </Sidebar>
      </main>
    </>
  );
};

export default Dashboard;
